<?php

namespace Raptor\Localization;

class TextInitial
{
    public static function localization_text_user(TextModel $model)
    {
        // ¯\_(:/)_/¯
    }

    public static function localization_text_default(TextModel $model)
    {
        // generated by codesaur | 2020-11-25 13:36:31 | ::1
        // model: Raptor\Localization\TextModel
        // table: default
        $model->insert(['keyword' => 'action', 'type' => 'sys-defined'], ['mn' => ['text' => 'Үйлдэл'], 'en' => ['text' => 'Action']]);
        $model->insert(['keyword' => 'address', 'type' => 'sys-defined'], ['mn' => ['text' => 'Хаяг'], 'en' => ['text' => 'Address']]);
        $model->insert(['keyword' => 'accept', 'type' => 'sys-defined'], ['mn' => ['text' => 'Зөвшөөрөх'], 'en' => ['text' => 'Accept']]);
        $model->insert(['keyword' => 'back', 'type' => 'sys-defined'], ['mn' => ['text' => 'Буцах'], 'en' => ['text' => 'Back']]);
        $model->insert(['keyword' => 'cancel', 'type' => 'sys-defined'], ['mn' => ['text' => 'Болих'], 'en' => ['text' => 'Cancel']]);
        $model->insert(['keyword' => 'category', 'type' => 'sys-defined'], ['mn' => ['text' => 'Ангилал'], 'en' => ['text' => 'Category']]);
        $model->insert(['keyword' => 'change', 'type' => 'sys-defined'], ['mn' => ['text' => 'Өөрчлөх'], 'en' => ['text' => 'Change']]);
        $model->insert(['keyword' => 'close', 'type' => 'sys-defined'], ['mn' => ['text' => 'Хаах'], 'en' => ['text' => 'Close']]);
        $model->insert(['keyword' => 'code', 'type' => 'sys-defined'], ['mn' => ['text' => 'Код'], 'en' => ['text' => 'Code']]);
        $model->insert(['keyword' => 'comment', 'type' => 'sys-defined'], ['mn' => ['text' => 'Сэтгэгдэл'], 'en' => ['text' => 'Comment']]);
        $model->insert(['keyword' => 'confirm', 'type' => 'sys-defined'], ['mn' => ['text' => 'Батлах'], 'en' => ['text' => 'Confirm']]);
        $model->insert(['keyword' => 'contact', 'type' => 'sys-defined'], ['mn' => ['text' => 'Холбоо барих'], 'en' => ['text' => 'Contact']]);
        $model->insert(['keyword' => 'content', 'type' => 'sys-defined'], ['mn' => ['text' => 'Агуулга'], 'en' => ['text' => 'Content']]);
        $model->insert(['keyword' => 'continue', 'type' => 'sys-defined'], ['mn' => ['text' => 'Үргэлжлүүлэх'], 'en' => ['text' => 'Continue']]);
        $model->insert(['keyword' => 'config', 'type' => 'sys-defined'], ['en' => ['text' => 'Config'], 'mn' => ['text' => 'Тохиргоо']]);
        $model->insert(['keyword' => 'dashboard', 'type' => 'sys-defined'], ['mn' => ['text' => 'Хянах самбар'], 'en' => ['text' => 'Dashboard']]);
        $model->insert(['keyword' => 'date', 'type' => 'sys-defined'], ['mn' => ['text' => 'Он сар'], 'en' => ['text' => 'Date']]);
        $model->insert(['keyword' => 'delete', 'type' => 'sys-defined'], ['mn' => ['text' => 'Устгах'], 'en' => ['text' => 'Delete']]);
        $model->insert(['keyword' => 'email', 'type' => 'sys-defined'], ['mn' => ['text' => 'Имэйл'], 'en' => ['text' => 'Email']]);
        $model->insert(['keyword' => 'error', 'type' => 'sys-defined'], ['mn' => ['text' => 'Алдаа'], 'en' => ['text' => 'Error']]);
        $model->insert(['keyword' => 'file', 'type' => 'sys-defined'], ['mn' => ['text' => 'Файл'], 'en' => ['text' => 'File']]);
        $model->insert(['keyword' => 'files', 'type' => 'sys-defined'], ['en' => ['text' => 'Files'], 'mn' => ['text' => 'Файлууд']]);
        $model->insert(['keyword' => 'filter', 'type' => 'sys-defined'], ['en' => ['text' => 'Filter'], 'mn' => ['text' => 'Шүүлтүүр']]);
        $model->insert(['keyword' => 'firstname', 'type' => 'sys-defined'], ['mn' => ['text' => 'Нэр'], 'en' => ['text' => 'First Name']]);
        $model->insert(['keyword' => 'flag', 'type' => 'sys-defined'], ['en' => ['text' => 'Flag'], 'mn' => ['text' => 'Далбаа']]);
        $model->insert(['keyword' => 'home', 'type' => 'sys-defined'], ['en' => ['text' => 'Home'], 'mn' => ['text' => 'Нүүр']]);
        $model->insert(['keyword' => 'keyword', 'type' => 'sys-defined'], ['mn' => ['text' => 'Түлхүүр үг'], 'en' => ['text' => 'Keyword']]);
        $model->insert(['keyword' => 'language', 'type' => 'sys-defined'], ['en' => ['text' => 'Language'], 'mn' => ['text' => 'Хэл']]);
        $model->insert(['keyword' => 'lastname', 'type' => 'sys-defined'], ['mn' => ['text' => 'Овог'], 'en' => ['text' => 'Last name']]);
        $model->insert(['keyword' => 'list', 'type' => 'sys-defined'], ['mn' => ['text' => 'Жагсаалт'], 'en' => ['text' => 'List']]);
        $model->insert(['keyword' => 'loading', 'type' => 'sys-defined'], ['mn' => ['text' => 'Ачаалж байна'], 'en' => ['text' => 'Loading']]);
        $model->insert(['keyword' => 'log', 'type' => 'sys-defined'], ['mn' => ['text' => 'Протокол'], 'en' => ['text' => 'Log']]);
        $model->insert(['keyword' => 'logs', 'type' => 'sys-defined'], ['mn' => ['text' => 'Протокол'], 'en' => ['text' => 'Logs']]);
        $model->insert(['keyword' => 'login', 'type' => 'sys-defined'], ['en' => ['text' => 'Login'], 'mn' => ['text' => 'Нэвтрэх']]);
        $model->insert(['keyword' => 'signin', 'type' => 'sys-defined'], ['en' => ['text' => 'Sign In'], 'mn' => ['text' => 'Нэвтрэх']]);
        $model->insert(['keyword' => 'logout', 'type' => 'sys-defined'], ['en' => ['text' => 'Logout'], 'mn' => ['text' => 'Гарах']]);
        $model->insert(['keyword' => 'localization', 'type' => 'sys-defined'], ['mn' => ['text' => 'Нутагшуулалт'], 'en' => ['text' => 'Localization']]);
        $model->insert(['keyword' => 'menu', 'type' => 'sys-defined'], ['mn' => ['text' => 'Меню'], 'en' => ['text' => 'Menu']]);
        $model->insert(['keyword' => 'meta', 'type' => 'sys-defined'], ['mn' => ['text' => 'Мета'], 'en' => ['text' => 'Meta']]);
        $model->insert(['keyword' => 'name', 'type' => 'sys-defined'], ['mn' => ['text' => 'Нэр'], 'en' => ['text' => 'Name']]);
        $model->insert(['keyword' => 'new', 'type' => 'sys-defined'], ['mn' => ['text' => 'Шинэ'], 'en' => ['text' => 'New']]);
        $model->insert(['keyword' => 'news', 'type' => 'sys-defined'], ['mn' => ['text' => 'Мэдээлэл'], 'en' => ['text' => 'News']]);
        $model->insert(['keyword' => 'no', 'type' => 'sys-defined'], ['mn' => ['text' => 'Үгүй'], 'en' => ['text' => 'No']]);
        $model->insert(['keyword' => 'notice', 'type' => 'sys-defined'], ['mn' => ['text' => 'Мэдэгдэл'], 'en' => ['text' => 'Notice']]);
        $model->insert(['keyword' => 'pages', 'type' => 'sys-defined'], ['mn' => ['text' => 'Хуудсууд'], 'en' => ['text' => 'Pages']]);
        $model->insert(['keyword' => 'password', 'type' => 'sys-defined'], ['mn' => ['text' => 'Нууц үг'], 'en' => ['text' => 'Password']]);
        $model->insert(['keyword' => 'phone', 'type' => 'sys-defined'], ['mn' => ['text' => 'Утас'], 'en' => ['text' => 'Phone']]);
        $model->insert(['keyword' => 'photo', 'type' => 'sys-defined'], ['mn' => ['text' => 'Зураг'], 'en' => ['text' => 'Photo']]);
        $model->insert(['keyword' => 'position', 'type' => 'sys-defined'], ['mn' => ['text' => 'Байршил'], 'en' => ['text' => 'Position']]);
        $model->insert(['keyword' => 'read-more', 'type' => 'sys-defined'], ['mn' => ['text' => 'Дэлгэрэнгүй'], 'en' => ['text' => 'Read more']]);
        $model->insert(['keyword' => 'remove', 'type' => 'sys-defined'], ['mn' => ['text' => 'Арилгах'], 'en' => ['text' => 'Remove']]);
        $model->insert(['keyword' => 'recent-news', 'type' => 'sys-defined'], ['mn' => ['text' => 'Сүүлийн үеийн мэдээ'], 'en' => ['text' => 'Recent News']]);
        $model->insert(['keyword' => 'request', 'type' => 'sys-defined'], ['mn' => ['text' => 'Хүсэлт'], 'en' => ['text' => 'Request']]);
        $model->insert(['keyword' => 'role', 'type' => 'sys-defined'], ['mn' => ['text' => 'Дүр'], 'en' => ['text' => 'Role']]);
        $model->insert(['keyword' => 'save', 'type' => 'sys-defined'], ['mn' => ['text' => 'Хадгалах'], 'en' => ['text' => 'Save']]);
        $model->insert(['keyword' => 'search', 'type' => 'sys-defined'], ['mn' => ['text' => 'Хайх'], 'en' => ['text' => 'Search']]);
        $model->insert(['keyword' => 'select', 'type' => 'sys-defined'], ['mn' => ['text' => 'Сонгох'], 'en' => ['text' => 'Select']]);
        $model->insert(['keyword' => 'settings', 'type' => 'sys-defined'], ['mn' => ['text' => 'Тохиргоонууд'], 'en' => ['text' => 'Settings']]);
        $model->insert(['keyword' => 'signup', 'type' => 'sys-defined'], ['mn' => ['text' => 'Бүртгүүлэх'], 'en' => ['text' => 'Sign Up']]);
        $model->insert(['keyword' => 'sitemap', 'type' => 'sys-defined'], ['en' => ['text' => 'Site map'], 'mn' => ['text' => 'Сайтын бүтэц']]);
        $model->insert(['keyword' => 'status', 'type' => 'sys-defined'], ['mn' => ['text' => 'Төлөв'], 'en' => ['text' => 'Status']]);
        $model->insert(['keyword' => 'submit', 'type' => 'sys-defined'], ['mn' => ['text' => 'Батлах'], 'en' => ['text' => 'Submit']]);
        $model->insert(['keyword' => 'success', 'type' => 'sys-defined'], ['en' => ['text' => 'Success'], 'mn' => ['text' => 'Амжилттай']]);
        $model->insert(['keyword' => 'telephone', 'type' => 'sys-defined'], ['mn' => ['text' => 'Утас'], 'en' => ['text' => 'Telephone']]);
        $model->insert(['keyword' => 'title', 'type' => 'sys-defined'], ['en' => ['text' => 'Title'], 'mn' => ['text' => 'Гарчиг']]);
        $model->insert(['keyword' => 'type', 'type' => 'sys-defined'], ['mn' => ['text' => 'Төрөл'], 'en' => ['text' => 'Type']]);
        $model->insert(['keyword' => 'urgent', 'type' => 'sys-defined'], ['mn' => ['text' => 'Яаралтай'], 'en' => ['text' => 'Urgent']]);
        $model->insert(['keyword' => 'user', 'type' => 'sys-defined'], ['mn' => ['text' => 'Хэрэглэгч'], 'en' => ['text' => 'User']]);
        $model->insert(['keyword' => 'username', 'type' => 'sys-defined'], ['en' => ['text' => 'Username'], 'mn' => ['text' => 'Хэрэглэгчийн нэр']]);
        $model->insert(['keyword' => 'users', 'type' => 'sys-defined'], ['en' => ['text' => 'Users'], 'mn' => ['text' => 'Хэрэглэгчид']]);
        $model->insert(['keyword' => 'yes', 'type' => 'sys-defined'], ['en' => ['text' => 'Yes'], 'mn' => ['text' => 'Тийм']]);
        $model->insert(['keyword' => 'parent', 'type' => 'sys-defined'], ['mn' => ['text' => 'Эцэг'], 'en' => ['text' => 'Parent']]);
        $model->insert(['keyword' => 'description', 'type' => 'sys-defined'], ['mn' => ['text' => 'Тайлбар'], 'en' => ['text' => 'Description']]);
        $model->insert(['keyword' => 'logo', 'type' => 'sys-defined'], ['mn' => ['text' => 'Лого'], 'en' => ['text' => 'Logo']]);
        $model->insert(['keyword' => 'image', 'type' => 'sys-defined'], ['mn' => ['text' => 'Зураг'], 'en' => ['text' => 'Image']]);
        $model->insert(['keyword' => 'publish', 'type' => 'sys-defined'], ['mn' => ['text' => 'Нийтлэх'], 'en' => ['text' => 'Publish']]);
        $model->insert(['keyword' => 'follow-us', 'type' => 'sys-defined'], ['mn' => ['text' => 'Биднийг дагах'], 'en' => ['text' => 'Follow Us']]);
        $model->insert(['keyword' => 'enter-search-terms', 'type' => 'sys-defined'], ['mn' => ['text' => 'Хайх утгаа оруулна уу..'], 'en' => ['text' => 'Enter search terms..']]);
        $model->insert(['keyword' => 'warning', 'type' => 'sys-defined'], ['en' => ['text' => 'Warning'], 'mn' => ['text' => 'Сануулга']]);
        $model->insert(['keyword' => 'version', 'type' => 'sys-defined'], ['en' => ['text' => 'Version'], 'mn' => ['text' => 'Хувилбар']]);
        $model->insert(['keyword' => 'options', 'type' => 'sys-defined'], ['en' => ['text' => 'Options'], 'mn' => ['text' => 'Сонголтууд']]);
        $model->insert(['keyword' => 'link', 'type' => 'sys-defined'], ['mn' => ['text' => 'Холбоос'], 'en' => ['text' => 'Link']]);
        $model->insert(['keyword' => 'choose', 'type' => 'sys-defined'], ['mn' => ['text' => 'Сонгох'], 'en' => ['text' => 'Choose']]);
        $model->insert(['keyword' => 'organization', 'type' => 'sys-defined'], ['mn' => ['text' => 'Байгууллага'], 'en' => ['text' => 'Organization']]);
        $model->insert(['keyword' => 'organizations', 'type' => 'sys-defined'], ['mn' => ['text' => 'Байгууллагууд'], 'en' => ['text' => 'Organizations']]);
        $model->insert(['keyword' => 'properties', 'type' => 'sys-defined'], ['mn' => ['text' => 'Шинж чанарууд'], 'en' => ['text' => 'Properties']]);
        $model->insert(['keyword' => 'group', 'type' => 'sys-defined'], ['mn' => ['text' => 'Бүлэг'], 'en' => ['text' => 'Group']]);
    }
    
    public static function localization_text_dashboard(TextModel $model)
    {
        // generated by codesaur | 2024-09-20 13:24:31 | ::1
        // model: Raptor\Localization\TextModel
        // table: dashboard
        $model->insert(['keyword' => 'general-info', 'type' => 'sys-defined'], ['mn' => ['text' => 'Ерөнхий мэдээлэл'], 'en' => ['text' => 'General Info']]);
        $model->insert(['keyword' => 'reference-tables', 'type' => 'sys-defined'], ['mn' => ['text' => 'Лавлах хүснэгтүүд'], 'en' => ['text' => 'Reference Tables']]);
        $model->insert(['keyword' => 'text-settings', 'type' => 'sys-defined'], ['en' => ['text' => 'Text Settings'], 'mn' => ['text' => 'Текстийн тохиргоо']]);
        $model->insert(['keyword' => 'select-an-image', 'type' => 'sys-defined'], ['mn' => ['text' => 'Зураг сонгох'], 'en' => ['text' => 'Select an Image']]);
        $model->insert(['keyword' => 'field-is-required', 'type' => 'sys-defined'], ['en' => ['text' => 'This field is required'], 'mn' => ['text' => 'Талбарын утгыг оруулна уу']]);
        $model->insert(['keyword' => 'please-confirm-info', 'type' => 'sys-defined'], ['mn' => ['text' => 'Мэдээллийг баталгаажуулна уу'], 'en' => ['text' => 'Please confirm infomations']]);
        $model->insert(['keyword' => 'enter-valid-email', 'type' => 'sys-defined'], ['en' => ['text' => 'Please enter a valid email address'], 'mn' => ['text' => 'Имэйл хаягыг зөв оруулна уу']]);
        $model->insert(['keyword' => 'email-template-not-set', 'type' => 'sys-defined'], ['en' => ['text' => 'Email template not found!'], 'mn' => ['text' => 'Цахим захианы загварыг тодорхойлоогүй байна!']]);
        $model->insert(['keyword' => 'record-successfully-deleted', 'type' => 'sys-defined'], ['en' => ['text' => 'Record successfully deleted'], 'mn' => ['text' => 'Бичлэг амжилттай устлаа']]);
        $model->insert(['keyword' => 'created-by', 'type' => 'sys-defined'], ['mn' => ['text' => 'Үүсгэсэн хэрэглэгч'], 'en' => ['text' => 'Created by']]);
        $model->insert(['keyword' => 'date-created', 'type' => 'sys-defined'], ['mn' => ['text' => 'Үүссэн огноо'], 'en' => ['text' => 'Date created']]);
        $model->insert(['keyword' => 'updated-by', 'type' => 'sys-defined'], ['mn' => ['text' => 'Өөрчилсөн хэрэглэгч'], 'en' => ['text' => 'Modified by']]);
        $model->insert(['keyword' => 'date-modified', 'type' => 'sys-defined'], ['mn' => ['text' => 'Өөрчлөгдсөн огноо'], 'en' => ['text' => 'Date modified']]);
        $model->insert(['keyword' => 'invalid-values', 'type' => 'sys-defined'], ['mn' => ['text' => 'Утга буруу байна!'], 'en' => ['text' => 'Invalid values!']]);
        $model->insert(['keyword' => 'invalid-request', 'type' => 'sys-defined'], ['en' => ['text' => 'Request is not valid!'], 'mn' => ['text' => 'Хүсэлт буруу байна!']]);
        $model->insert(['keyword' => 'system-no-permission', 'type' => 'sys-defined'], ['mn' => ['text' => 'Уучлаарай, таньд энэ мэдээлэлд хандах эрх олгогдоогүй байна!'], 'en' => ['text' => 'Access Denied, You don\'t have permission to access on this resource!']]);
        $model->insert(['keyword' => 'can-comment', 'type' => 'sys-defined'], ['en' => ['text' => 'Can user comment on this post?'], 'mn' => ['text' => 'Хэрэглэгч сэтгэгдэл үлдээж(бичиж) болох эсэх']]);
        $model->insert(['keyword' => 'no-record-selected', 'type' => 'sys-defined'], ['en' => ['text' => 'No record selected'], 'mn' => ['text' => 'Бичлэг сонгогдоогүй байна']]);
        $model->insert(['keyword' => 'select-files', 'type' => 'sys-defined'], ['mn' => ['text' => 'Файлуудыг сонгох'], 'en' => ['text' => 'Select Files']]);
        $model->insert(['keyword' => 'upload-files', 'type' => 'sys-defined'], ['mn' => ['text' => 'Файлуудыг илгээх'], 'en' => ['text' => 'Upload Files']]);
        $model->insert(['keyword' => 'u-have-some-form-errors', 'type' => 'sys-defined'], ['en' => ['text' => 'You have some form errors. Please check below'], 'mn' => ['text' => 'Та мэдээллийг алдаатай бөглөсөн байна. Доорх талбаруудаа шалгана уу']]);
        $model->insert(['keyword' => 'add-record', 'type' => 'sys-defined'], ['en' => ['text' => 'Add Record'], 'mn' => ['text' => 'Бичлэг нэмэх']]);
        $model->insert(['keyword' => 'edit-record', 'type' => 'sys-defined'], ['en' => ['text' => 'Edit Record'], 'mn' => ['text' => 'Бичлэг засах']]);
        $model->insert(['keyword' => 'view-record', 'type' => 'sys-defined'], ['mn' => ['text' => 'Бичлэг харах'], 'en' => ['text' => 'View record']]);
        $model->insert(['keyword' => 'keyword-existing-in', 'type' => 'sys-defined'], ['en' => ['text' => 'Keyword existing in'], 'mn' => ['text' => 'Түлхүүр үг давхцаж байна']]);
        $model->insert(['keyword' => 'record-insert-success', 'type' => 'sys-defined'], ['mn' => ['text' => 'Бичлэг амжилттай нэмэгдлээ'], 'en' => ['text' => 'Record successfully added']]);
        $model->insert(['keyword' => 'record-insert-error', 'type' => 'sys-defined'], ['en' => ['text' => 'Error occurred while inserting record'], 'mn' => ['text' => 'Бичлэг нэмэх явцад алдаа гарлаа']]);
        $model->insert(['keyword' => 'record-update-success', 'type' => 'sys-defined'], ['en' => ['text' => 'Record successfully updated'], 'mn' => ['text' => 'Бичлэг амжилттай засагдлаа']]);
        $model->insert(['keyword' => 'something-went-wrong', 'type' => 'sys-defined'], ['mn' => ['text' => 'Ямар нэгэн саатал учирлаа'], 'en' => ['text' => 'Looks like something went wrong']]);
        $model->insert(['keyword' => 'copy-text-from', 'type' => 'sys-defined'], ['mn' => ['text' => 'Текст хуулбарлах хэл'], 'en' => ['text' => 'Copy texts from']]);
        $model->insert(['keyword' => 'enter-language-details', 'type' => 'sys-defined'], ['mn' => ['text' => 'Хэлний мэдээллийг оруулна уу'], 'en' => ['text' => 'Provide language details']]);
        $model->insert(['keyword' => 'select-text-settings', 'type' => 'sys-defined'], ['mn' => ['text' => 'Текстийн тохиргоог сонгоно уу'], 'en' => ['text' => 'Select text settings']]);
        $model->insert(['keyword' => 'error-existing-lang-code', 'type' => 'sys-defined'], ['mn' => ['text' => 'Хэлний кодыг системд ашиглаж байгаа тул өөр код сонгоно уу!'], 'en' => ['text' => 'Хэлний кодыг системд ашиглаж байгаа тул өөр код сонгоно уу!']]);
        $model->insert(['keyword' => 'error-lang-existing', 'type' => 'sys-defined'], ['mn' => ['text' => 'Системд хэлийг ашиглаж байгаа тул өөр хэл сонгоно уу!'], 'en' => ['text' => 'Системд хэлийг ашиглаж байгаа тул өөр хэл сонгоно уу!']]);
        $model->insert(['keyword' => 'error-lang-name-existing', 'type' => 'sys-defined'], ['mn' => ['text' => 'Системд хэлний нэрийг ашиглаж байгаа тул өөр нэр ашиглана уу!'], 'en' => ['text' => 'Системд хэлний нэрийг ашиглаж байгаа тул өөр нэр ашиглана уу!']]);
        $model->insert(['keyword' => 'ask-dont-have-user-yet', 'type' => 'sys-defined'], ['en' => ['text' => 'Don\'t have an user yet?'], 'mn' => ['text' => 'Хэрэглэгч болж амжаагүй байна уу?']]);
        $model->insert(['keyword' => 'enter-email-below', 'type' => 'sys-defined'], ['en' => ['text' => 'Enter your e-mail address!'], 'mn' => ['text' => 'Бүртгэлтэй имэйл хаягаа доор бичнэ үү!']]);
        $model->insert(['keyword' => 'enter-personal-details', 'type' => 'sys-defined'], ['mn' => ['text' => 'Та доор хэсэгт хувийн мэдээллээ оруулна уу!'], 'en' => ['text' => 'Enter your personal details below!']]);
        $model->insert(['keyword' => 'error-password-empty', 'type' => 'sys-defined'], ['en' => ['text' => 'Please enter password'], 'mn' => ['text' => 'Нууц үг талбарыг оруулна уу']]);
        $model->insert(['keyword' => 'error-username-empty', 'type' => 'sys-defined'], ['en' => ['text' => 'Please enter username'], 'mn' => ['text' => 'Нэвтрэх нэр талбарыг оруулна уу']]);
        $model->insert(['keyword' => 'enter-email-empty', 'type' => 'sys-defined'], ['en' => ['text' => 'Please enter email address'], 'mn' => ['text' => 'Имейл хаягыг оруулна уу']]);
        $model->insert(['keyword' => 'forgot-password', 'type' => 'sys-defined'], ['en' => ['text' => 'Forgot password?'], 'mn' => ['text' => 'Нууц үгээ мартсан уу?']]);
        $model->insert(['keyword' => 'reset-email-sent', 'type' => 'sys-defined'], ['en' => ['text' => 'An reset e-mail has been sent.<br />Please check your email for further instructions!'], 'mn' => ['text' => 'Нууц үгийг шинэчлэх зааврыг амжилттай илгээлээ.<br />Та заасан имейл хаягаа шалгаж зааврын дагуу нууц үгээ шинэчлэнэ үү!']]);
        $model->insert(['keyword' => 'password-reset', 'type' => 'sys-defined'], ['mn' => ['text' => 'Нууц үг шинээр тааруулах'], 'en' => ['text' => 'Password reset']]);
        $model->insert(['keyword' => 'set-new-password', 'type' => 'sys-defined'], ['en' => ['text' => 'Please set a new password for the user!'], 'mn' => ['text' => 'Хэрэглэгчийн шинэ нууц үгийг тохируулна уу!']]);
        $model->insert(['keyword' => 'retype-password', 'type' => 'sys-defined'], ['en' => ['text' => 'Re-type Password'], 'mn' => ['text' => 'Нууц үгээ дахин бичнэ']]);
        $model->insert(['keyword' => 'set-new-password-success', 'type' => 'sys-defined'], ['en' => ['text' => 'Your password has been changed successfully! Thank you'], 'mn' => ['text' => 'Нууц үгийг шинээр тохирууллаа. Шинэ нууц үгээ ашиглана уу']]);
        $model->insert(['keyword' => 'fill-new-password', 'type' => 'sys-defined'], ['en' => ['text' => 'Please fill a new password!'], 'mn' => ['text' => 'Шинэ нууц үгийг оруулна уу!']]);
        $model->insert(['keyword' => 'password-must-confirm', 'type' => 'sys-defined'], ['en' => ['text' => 'Please re-enter the password'], 'mn' => ['text' => 'Нууц үгийг давтан бичих хэрэгтэй']]);
        $model->insert(['keyword' => 'password-must-match', 'type' => 'sys-defined'], ['en' => ['text' => 'Password entries must match'], 'mn' => ['text' => 'Нууц үгийг давтан бичихдээ зөв оруулах хэрэгтэй']]);
        $model->insert(['keyword' => 'to-complete-registration-check-email', 'type' => 'sys-defined'], ['en' => ['text' => 'Thank you. To complete your registration please check your email'], 'mn' => ['text' => 'Танд баярлалаа. Бүртгэлээ баталгаажуулахын тулд заасан имейлээ шалгана уу']]);
        $model->insert(['keyword' => 'active-user-can-login', 'type' => 'sys-defined'], ['en' => ['text' => 'only active users can login'], 'mn' => ['text' => 'зөвхөн идэвхитэй хэрэглэгч системд нэвтэрч чадна']]);
        $model->insert(['keyword' => 'create-new-user', 'type' => 'sys-defined'], ['en' => ['text' => 'Create new user'], 'mn' => ['text' => 'Хэрэглэгч шинээр үүсгэх']]);
        $model->insert(['keyword' => 'personal-info', 'type' => 'sys-defined'], ['en' => ['text' => 'Personal Info'], 'mn' => ['text' => 'Хувийн мэдээлэл']]);
        $model->insert(['keyword' => 'new-password', 'type' => 'sys-defined'], ['mn' => ['text' => 'Шинэ нууц үг'], 'en' => ['text' => 'New Password']]);
        $model->insert(['keyword' => 'retype-new-password', 'type' => 'sys-defined'], ['en' => ['text' => 'Re-type New Password'], 'mn' => ['text' => 'Шинэ нууц үгийг давтах']]);
        $model->insert(['keyword' => 'edit-user', 'type' => 'sys-defined'], ['en' => ['text' => 'Edit user information'], 'mn' => ['text' => 'Хэрэглэгчийн мэдээлэл өөрчлөх']]);
        $model->insert(['keyword' => 'user-exists', 'type' => 'sys-defined'], ['en' => ['text' => 'It looks like information belongs to an existing user'], 'mn' => ['text' => 'Заасан мэдээлэл бүхий хэрэглэгч аль хэдийн бүртгэгдсэн байна']]);
        $model->insert(['keyword' => 'request-new-user', 'type' => 'sys-defined'], ['mn' => ['text' => 'Хэрэглэгчээр бүртгүүлэх хүсэлт'], 'en' => ['text' => 'Request a new user']]);
    }
}
